import { BookingResponse, DiscoverResponse } from "@/lib/types";

export const demoDiscoverResponse: DiscoverResponse = {
  destination: "Goa",
  nights: 2,
  guests: 2,
  matchingHotels: 6,
  spotlight: [
    {
      title: "No hidden fees",
      subtitle: "Every card shows taxes included before checkout.",
      tone: "mint",
    },
    {
      title: "Verified imagery",
      subtitle: "Community photos and authenticity checks stay visible.",
      tone: "sky",
    },
    {
      title: "Emergency desk",
      subtitle: "24/7 help line and one-tap trip support are live.",
      tone: "amber",
    },
  ],
  hotels: [
    {
      id: 1,
      slug: "lagoon-house-goa",
      name: "Lagoon House Goa",
      city: "Goa",
      area: "Candolim",
      addressLine: "Fort Aguada Road, Candolim, North Goa",
      landmark: "Near Candolim Beach",
      propertyType: "Resort",
      description: "Quiet coastal stay with verified photos, transparent taxes, and fast support for late arrivals.",
      nightlyRate: 4200,
      taxesAndFees: 780,
      totalPrice: 9960,
      rating: 4.8,
      reviewCount: 312,
      safetyScore: 92,
      distanceToCenterKm: 2.1,
      distanceToAirportKm: 34,
      distanceToMetroKm: 0.9,
      latitude: 15.5176,
      longitude: 73.7627,
      availableNow: true,
      freeCancellation: true,
      payAtHotel: true,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: true,
      breakfastIncluded: true,
      coupleFriendly: true,
      discountPercent: 18,
      loyaltyProgress: 74,
      priceDropLabel: "Price dropped 12% in the last 6 hours",
      responseTime: "2 min",
      supportLevel: "24/7 concierge",
      tags: ["safe", "family-friendly", "walkable"],
      amenities: ["Pool", "Breakfast", "Airport pickup", "Workspace"],
      imageUrls: [
        "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Aarav", stayType: "Family stay", rating: 4.8, verifiedStay: true, flaggedAsAuthentic: true, comment: "Every rupee was visible before checkout and the beach cab arrived exactly on time." },
        { author: "Maya", stayType: "Weekend escape", rating: 4.7, verifiedStay: true, flaggedAsAuthentic: true, comment: "Photos matched reality, and support helped us move the booking in under three minutes." },
      ],
    },
    {
      id: 2,
      slug: "atlas-bay-suites",
      name: "Atlas Bay Suites",
      city: "Goa",
      area: "Panaji",
      addressLine: "Rua de Ourem, Fontainhas, Panaji, Goa",
      landmark: "Near riverfront promenade",
      propertyType: "Hotel",
      description: "Premium business-meets-leisure suite hotel close to nightlife, riverfront dining, and transit.",
      nightlyRate: 5100,
      taxesAndFees: 920,
      totalPrice: 12040,
      rating: 4.6,
      reviewCount: 221,
      safetyScore: 88,
      distanceToCenterKm: 1.4,
      distanceToAirportKm: 28,
      distanceToMetroKm: 0.6,
      latitude: 15.4989,
      longitude: 73.8278,
      availableNow: true,
      freeCancellation: true,
      payAtHotel: false,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: false,
      breakfastIncluded: false,
      coupleFriendly: true,
      discountPercent: 0,
      loyaltyProgress: 61,
      priceDropLabel: "3 rooms left at this rate",
      responseTime: "5 min",
      supportLevel: "Priority desk",
      tags: ["nightlife", "business", "central"],
      amenities: ["Sky bar", "Gym", "Late checkout", "Meeting pod"],
      imageUrls: [
        "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Ishita", stayType: "Business trip", rating: 4.6, verifiedStay: true, flaggedAsAuthentic: true, comment: "Fast Wi-Fi, polished rooms, and the policy icons made rebooking really easy." },
      ],
    },
    {
      id: 3,
      slug: "palma-court",
      name: "Palma Court",
      city: "Goa",
      area: "Morjim",
      addressLine: "Morjim Ashwem Road, Pernem, Goa",
      landmark: "Opposite turtle beach access",
      propertyType: "Beach stay",
      description: "A design-forward beachfront stay with honest pricing, child-friendly services, and calm evenings.",
      nightlyRate: 3900,
      taxesAndFees: 690,
      totalPrice: 9180,
      rating: 4.7,
      reviewCount: 184,
      safetyScore: 95,
      distanceToCenterKm: 3.6,
      distanceToAirportKm: 42,
      distanceToMetroKm: 1.7,
      latitude: 15.6309,
      longitude: 73.7391,
      availableNow: true,
      freeCancellation: true,
      payAtHotel: true,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: true,
      breakfastIncluded: true,
      coupleFriendly: false,
      discountPercent: 22,
      loyaltyProgress: 82,
      priceDropLabel: "Tonight deal unlocked",
      responseTime: "1 min",
      supportLevel: "Rapid response",
      tags: ["family-friendly", "beachfront", "safe"],
      amenities: ["Kids club", "Beach transfer", "All-day cafe", "Laundry"],
      imageUrls: [
        "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Rohan", stayType: "Family stay", rating: 4.9, verifiedStay: true, flaggedAsAuthentic: true, comment: "The child-friendly tag was accurate and the taxes were already included on the first screen." },
      ],
    },
    {
      id: 4,
      slug: "drift-studio-stays",
      name: "Drift Studio Stays",
      city: "Goa",
      area: "Anjuna",
      addressLine: "St. Michael Vaddo, Anjuna, Goa",
      landmark: "5 minutes from Anjuna flea market",
      propertyType: "Apartment",
      description: "Flexible pay-at-hotel loft stay built for solo travelers, remote work, and quick beach access.",
      nightlyRate: 2800,
      taxesAndFees: 460,
      totalPrice: 6520,
      rating: 4.5,
      reviewCount: 147,
      safetyScore: 84,
      distanceToCenterKm: 2.9,
      distanceToAirportKm: 39,
      distanceToMetroKm: 1.1,
      latitude: 15.574,
      longitude: 73.7407,
      availableNow: true,
      freeCancellation: true,
      payAtHotel: true,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: false,
      breakfastIncluded: false,
      coupleFriendly: true,
      discountPercent: 0,
      loyaltyProgress: 58,
      priceDropLabel: "Popular with solo travelers this week",
      responseTime: "4 min",
      supportLevel: "Always-on chat",
      tags: ["solo", "nightlife", "budget"],
      amenities: ["Coworking lounge", "Bike rental", "Self check-in", "Cafe"],
      imageUrls: [
        "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1445019980597-93fa8acb246c?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Kabir", stayType: "Solo travel", rating: 4.5, verifiedStay: true, flaggedAsAuthentic: true, comment: "Flexible pay-at-hotel option made this the easiest last-minute pick." },
      ],
    },
    {
      id: 5,
      slug: "ember-square-inn",
      name: "Ember Square Inn",
      city: "Goa",
      area: "Baga",
      addressLine: "Tito's Lane extension, Baga, Goa",
      landmark: "Near Baga nightlife strip",
      propertyType: "Hotel",
      description: "Energetic last-minute base with nightlife access, accurate photos, and verified stay reviews.",
      nightlyRate: 3300,
      taxesAndFees: 580,
      totalPrice: 7760,
      rating: 4.4,
      reviewCount: 198,
      safetyScore: 80,
      distanceToCenterKm: 1.9,
      distanceToAirportKm: 36,
      distanceToMetroKm: 1,
      latitude: 15.5553,
      longitude: 73.7517,
      availableNow: true,
      freeCancellation: false,
      payAtHotel: true,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: true,
      breakfastIncluded: true,
      coupleFriendly: true,
      discountPercent: 15,
      loyaltyProgress: 49,
      priceDropLabel: "8 people viewed this in the last hour",
      responseTime: "3 min",
      supportLevel: "Emergency line",
      tags: ["nightlife", "last-minute", "walkable"],
      amenities: ["Live music", "Airport shuttle", "Quick breakfast", "Late-night desk"],
      imageUrls: [
        "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1522798514-97ceb8c4f1c8?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Naina", stayType: "Friends trip", rating: 4.3, verifiedStay: true, flaggedAsAuthentic: true, comment: "Close to nightlife without the usual listing surprises." },
      ],
    },
    {
      id: 6,
      slug: "hush-garden-retreat",
      name: "Hush Garden Retreat",
      city: "Goa",
      area: "Assagao",
      addressLine: "Mapusa-Assagao Road, Bardez, Goa",
      landmark: "Near Assagao church district",
      propertyType: "Villa",
      description: "Peaceful villa-style retreat with high safety scores, quiet surroundings, and family-first hospitality.",
      nightlyRate: 4700,
      taxesAndFees: 840,
      totalPrice: 11080,
      rating: 4.9,
      reviewCount: 128,
      safetyScore: 97,
      distanceToCenterKm: 4.3,
      distanceToAirportKm: 44,
      distanceToMetroKm: 2,
      latitude: 15.6089,
      longitude: 73.7856,
      availableNow: false,
      freeCancellation: true,
      payAtHotel: false,
      verifiedPhotos: true,
      hiddenFeesFree: true,
      lastMinuteDeal: false,
      breakfastIncluded: false,
      coupleFriendly: false,
      discountPercent: 0,
      loyaltyProgress: 90,
      priceDropLabel: "Highly rated for child-friendly service",
      responseTime: "6 min",
      supportLevel: "White-glove support",
      tags: ["safe", "family-friendly", "quiet"],
      amenities: ["Garden dining", "Private cabana", "Spa", "Crib on request"],
      imageUrls: [
        "https://images.unsplash.com/photo-1578683010236-d716f9a3f461?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1468824357306-a439d58ccb1c?auto=format&fit=crop&w=1200&q=80",
        "https://images.unsplash.com/photo-1455587734955-081b22074882?auto=format&fit=crop&w=1200&q=80",
      ],
      reviews: [
        { author: "Devika", stayType: "Relaxation stay", rating: 4.9, verifiedStay: true, flaggedAsAuthentic: true, comment: "Felt safe, calm, and exactly like the photos." },
      ],
    },
  ],
  tonightDeals: [],
};

demoDiscoverResponse.tonightDeals = demoDiscoverResponse.hotels.filter((hotel) => hotel.lastMinuteDeal).slice(0, 3);

export function createDemoBooking(hotelName: string, totalPrice: number): BookingResponse {
  return {
    id: Date.now(),
    confirmationCode: `SE-DEMO-${String(Date.now()).slice(-6)}`,
    hotelName,
    totalPrice,
    supportMessage: "Demo booking complete. Connect a live backend to process real reservations.",
  };
}
